
SHOW_FIXTURE_DEBUG = False
SHOW_DEBUG = False

SHOW_GRANULAR_NAVIGATION_GRID = 0
SHOW_PATHFINDING_DEBUG = False
SHOW_BEST_POSITION_FINDER_DEBUG = False

PRINT_MAP_AT_END = True

DO_WAIT_KEY = 0

DO_SLOW_DOWN = False
SLOW_DOWN_S = 0.032


DO_SAVE_FIXTURE_DEBUG = 0
SAVE_FIXTURE_DEBUG_DIR = "/home/iitaadmin/simulated_rescue_maze/debug_imgs"