
SHOW_FIXTURE_DEBUG = False
SHOW_DEBUG = False

SHOW_GRANULAR_NAVIGATION_GRID = False
SHOW_PATHFINDING_DEBUG = False
SHOW_BEST_POSITION_FINDER_DEBUG = False

SHOW_MAP_AT_END = False

DO_WAIT_KEY = False

DO_SLOW_DOWN = False
SLOW_DOWN_S = 0.032


DO_SAVE_FIXTURE_DEBUG = False
SAVE_FIXTURE_DEBUG_DIR = "/home/iitaadmin/simulated_rescue_maze/debug_imgs"