
SHOW_FIXTURE_DEBUG = False
SHOW_DEBUG = False

SHOW_GRANULAR_NAVIGATION_GRID = True
SHOW_PATHFINDING_DEBUG = False
SHOW_BEST_POSITION_FINDER_DEBUG = False

PRINT_MAP_AT_END = True

DO_WAIT_KEY = True